// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgLite.proto

package com.yuntongxun.mcm.core.protobuf;

public final class MsgLite {
  private MsgLite() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MsgLiteInnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MsgLiteInner)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 protoType = 1;</code>
     *
     * <pre>
     *消息类型  参考文件：方法类型数值说明.txt
     * </pre>
     */
    boolean hasProtoType();
    /**
     * <code>optional uint32 protoType = 1;</code>
     *
     * <pre>
     *消息类型  参考文件：方法类型数值说明.txt
     * </pre>
     */
    int getProtoType();

    /**
     * <code>optional bytes protoData = 2;</code>
     *
     * <pre>
     *消息数据
     * </pre>
     */
    boolean hasProtoData();
    /**
     * <code>optional bytes protoData = 2;</code>
     *
     * <pre>
     *消息数据
     * </pre>
     */
    com.google.protobuf.ByteString getProtoData();

    /**
     * <code>optional uint32 protoClientNo = 3;</code>
     *
     * <pre>
     *用于存放客户端流水号
     * </pre>
     */
    boolean hasProtoClientNo();
    /**
     * <code>optional uint32 protoClientNo = 3;</code>
     *
     * <pre>
     *用于存放客户端流水号
     * </pre>
     */
    int getProtoClientNo();

    /**
     * <code>optional string protoBackExp = 4;</code>
     *
     * <pre>
     *用于存放后台模块的扩展信息
     * </pre>
     */
    boolean hasProtoBackExp();
    /**
     * <code>optional string protoBackExp = 4;</code>
     *
     * <pre>
     *用于存放后台模块的扩展信息
     * </pre>
     */
    java.lang.String getProtoBackExp();
    /**
     * <code>optional string protoBackExp = 4;</code>
     *
     * <pre>
     *用于存放后台模块的扩展信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getProtoBackExpBytes();

    /**
     * <code>optional string protoSource = 5;</code>
     *
     * <pre>
     *用于存放生产者源地址
     * </pre>
     */
    boolean hasProtoSource();
    /**
     * <code>optional string protoSource = 5;</code>
     *
     * <pre>
     *用于存放生产者源地址
     * </pre>
     */
    java.lang.String getProtoSource();
    /**
     * <code>optional string protoSource = 5;</code>
     *
     * <pre>
     *用于存放生产者源地址
     * </pre>
     */
    com.google.protobuf.ByteString
        getProtoSourceBytes();

    /**
     * <code>optional uint32 protoErrorCode = 6;</code>
     *
     * <pre>
     *服务器返回错误码
     * </pre>
     */
    boolean hasProtoErrorCode();
    /**
     * <code>optional uint32 protoErrorCode = 6;</code>
     *
     * <pre>
     *服务器返回错误码
     * </pre>
     */
    int getProtoErrorCode();

    /**
     * <code>optional uint32 protoEncrypt = 7;</code>
     *
     * <pre>
     *是否加密，有值就是加密
     * </pre>
     */
    boolean hasProtoEncrypt();
    /**
     * <code>optional uint32 protoEncrypt = 7;</code>
     *
     * <pre>
     *是否加密，有值就是加密
     * </pre>
     */
    int getProtoEncrypt();

    /**
     * <code>optional string protoToken = 8;</code>
     *
     * <pre>
     *精简认证token
     * </pre>
     */
    boolean hasProtoToken();
    /**
     * <code>optional string protoToken = 8;</code>
     *
     * <pre>
     *精简认证token
     * </pre>
     */
    java.lang.String getProtoToken();
    /**
     * <code>optional string protoToken = 8;</code>
     *
     * <pre>
     *精简认证token
     * </pre>
     */
    com.google.protobuf.ByteString
        getProtoTokenBytes();
  }
  /**
   * Protobuf type {@code MsgLiteInner}
   */
  public static final class MsgLiteInner extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:MsgLiteInner)
      MsgLiteInnerOrBuilder {
    // Use MsgLiteInner.newBuilder() to construct.
    private MsgLiteInner(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgLiteInner(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final MsgLiteInner defaultInstance;
    public static MsgLiteInner getDefaultInstance() {
      return defaultInstance;
    }

    public MsgLiteInner getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private MsgLiteInner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              protoType_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              protoData_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              protoClientNo_ = input.readUInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              protoBackExp_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              protoSource_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              protoErrorCode_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              protoEncrypt_ = input.readUInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              protoToken_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<MsgLiteInner> PARSER =
        new com.google.protobuf.AbstractParser<MsgLiteInner>() {
      public MsgLiteInner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgLiteInner(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgLiteInner> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PROTOTYPE_FIELD_NUMBER = 1;
    private int protoType_;
    /**
     * <code>optional uint32 protoType = 1;</code>
     *
     * <pre>
     *消息类型  参考文件：方法类型数值说明.txt
     * </pre>
     */
    public boolean hasProtoType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 protoType = 1;</code>
     *
     * <pre>
     *消息类型  参考文件：方法类型数值说明.txt
     * </pre>
     */
    public int getProtoType() {
      return protoType_;
    }

    public static final int PROTODATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString protoData_;
    /**
     * <code>optional bytes protoData = 2;</code>
     *
     * <pre>
     *消息数据
     * </pre>
     */
    public boolean hasProtoData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes protoData = 2;</code>
     *
     * <pre>
     *消息数据
     * </pre>
     */
    public com.google.protobuf.ByteString getProtoData() {
      return protoData_;
    }

    public static final int PROTOCLIENTNO_FIELD_NUMBER = 3;
    private int protoClientNo_;
    /**
     * <code>optional uint32 protoClientNo = 3;</code>
     *
     * <pre>
     *用于存放客户端流水号
     * </pre>
     */
    public boolean hasProtoClientNo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 protoClientNo = 3;</code>
     *
     * <pre>
     *用于存放客户端流水号
     * </pre>
     */
    public int getProtoClientNo() {
      return protoClientNo_;
    }

    public static final int PROTOBACKEXP_FIELD_NUMBER = 4;
    private java.lang.Object protoBackExp_;
    /**
     * <code>optional string protoBackExp = 4;</code>
     *
     * <pre>
     *用于存放后台模块的扩展信息
     * </pre>
     */
    public boolean hasProtoBackExp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string protoBackExp = 4;</code>
     *
     * <pre>
     *用于存放后台模块的扩展信息
     * </pre>
     */
    public java.lang.String getProtoBackExp() {
      java.lang.Object ref = protoBackExp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          protoBackExp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string protoBackExp = 4;</code>
     *
     * <pre>
     *用于存放后台模块的扩展信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProtoBackExpBytes() {
      java.lang.Object ref = protoBackExp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protoBackExp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOSOURCE_FIELD_NUMBER = 5;
    private java.lang.Object protoSource_;
    /**
     * <code>optional string protoSource = 5;</code>
     *
     * <pre>
     *用于存放生产者源地址
     * </pre>
     */
    public boolean hasProtoSource() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string protoSource = 5;</code>
     *
     * <pre>
     *用于存放生产者源地址
     * </pre>
     */
    public java.lang.String getProtoSource() {
      java.lang.Object ref = protoSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          protoSource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string protoSource = 5;</code>
     *
     * <pre>
     *用于存放生产者源地址
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProtoSourceBytes() {
      java.lang.Object ref = protoSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protoSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOERRORCODE_FIELD_NUMBER = 6;
    private int protoErrorCode_;
    /**
     * <code>optional uint32 protoErrorCode = 6;</code>
     *
     * <pre>
     *服务器返回错误码
     * </pre>
     */
    public boolean hasProtoErrorCode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 protoErrorCode = 6;</code>
     *
     * <pre>
     *服务器返回错误码
     * </pre>
     */
    public int getProtoErrorCode() {
      return protoErrorCode_;
    }

    public static final int PROTOENCRYPT_FIELD_NUMBER = 7;
    private int protoEncrypt_;
    /**
     * <code>optional uint32 protoEncrypt = 7;</code>
     *
     * <pre>
     *是否加密，有值就是加密
     * </pre>
     */
    public boolean hasProtoEncrypt() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 protoEncrypt = 7;</code>
     *
     * <pre>
     *是否加密，有值就是加密
     * </pre>
     */
    public int getProtoEncrypt() {
      return protoEncrypt_;
    }

    public static final int PROTOTOKEN_FIELD_NUMBER = 8;
    private java.lang.Object protoToken_;
    /**
     * <code>optional string protoToken = 8;</code>
     *
     * <pre>
     *精简认证token
     * </pre>
     */
    public boolean hasProtoToken() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string protoToken = 8;</code>
     *
     * <pre>
     *精简认证token
     * </pre>
     */
    public java.lang.String getProtoToken() {
      java.lang.Object ref = protoToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          protoToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string protoToken = 8;</code>
     *
     * <pre>
     *精简认证token
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProtoTokenBytes() {
      java.lang.Object ref = protoToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protoToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      protoType_ = 0;
      protoData_ = com.google.protobuf.ByteString.EMPTY;
      protoClientNo_ = 0;
      protoBackExp_ = "";
      protoSource_ = "";
      protoErrorCode_ = 0;
      protoEncrypt_ = 0;
      protoToken_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, protoType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, protoData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, protoClientNo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getProtoBackExpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getProtoSourceBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, protoErrorCode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, protoEncrypt_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getProtoTokenBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, protoType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, protoData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, protoClientNo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getProtoBackExpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getProtoSourceBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, protoErrorCode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, protoEncrypt_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getProtoTokenBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code MsgLiteInner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:MsgLiteInner)
        com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInnerOrBuilder {
      // Construct using com.yuntongxun.logic.core.protobuf.MsgLite.MsgLiteInner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        protoType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        protoData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        protoClientNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        protoBackExp_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        protoSource_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        protoErrorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        protoEncrypt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        protoToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner getDefaultInstanceForType() {
        return com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner.getDefaultInstance();
      }

      public com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner build() {
        com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner buildPartial() {
        com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner result = new com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protoType_ = protoType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.protoData_ = protoData_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.protoClientNo_ = protoClientNo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.protoBackExp_ = protoBackExp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.protoSource_ = protoSource_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.protoErrorCode_ = protoErrorCode_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.protoEncrypt_ = protoEncrypt_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.protoToken_ = protoToken_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner other) {
        if (other == com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner.getDefaultInstance()) return this;
        if (other.hasProtoType()) {
          setProtoType(other.getProtoType());
        }
        if (other.hasProtoData()) {
          setProtoData(other.getProtoData());
        }
        if (other.hasProtoClientNo()) {
          setProtoClientNo(other.getProtoClientNo());
        }
        if (other.hasProtoBackExp()) {
          bitField0_ |= 0x00000008;
          protoBackExp_ = other.protoBackExp_;
          
        }
        if (other.hasProtoSource()) {
          bitField0_ |= 0x00000010;
          protoSource_ = other.protoSource_;
          
        }
        if (other.hasProtoErrorCode()) {
          setProtoErrorCode(other.getProtoErrorCode());
        }
        if (other.hasProtoEncrypt()) {
          setProtoEncrypt(other.getProtoEncrypt());
        }
        if (other.hasProtoToken()) {
          bitField0_ |= 0x00000080;
          protoToken_ = other.protoToken_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yuntongxun.mcm.core.protobuf.MsgLite.MsgLiteInner) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int protoType_ ;
      /**
       * <code>optional uint32 protoType = 1;</code>
       *
       * <pre>
       *消息类型  参考文件：方法类型数值说明.txt
       * </pre>
       */
      public boolean hasProtoType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 protoType = 1;</code>
       *
       * <pre>
       *消息类型  参考文件：方法类型数值说明.txt
       * </pre>
       */
      public int getProtoType() {
        return protoType_;
      }
      /**
       * <code>optional uint32 protoType = 1;</code>
       *
       * <pre>
       *消息类型  参考文件：方法类型数值说明.txt
       * </pre>
       */
      public Builder setProtoType(int value) {
        bitField0_ |= 0x00000001;
        protoType_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 protoType = 1;</code>
       *
       * <pre>
       *消息类型  参考文件：方法类型数值说明.txt
       * </pre>
       */
      public Builder clearProtoType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protoType_ = 0;
        
        return this;
      }

      private com.google.protobuf.ByteString protoData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes protoData = 2;</code>
       *
       * <pre>
       *消息数据
       * </pre>
       */
      public boolean hasProtoData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes protoData = 2;</code>
       *
       * <pre>
       *消息数据
       * </pre>
       */
      public com.google.protobuf.ByteString getProtoData() {
        return protoData_;
      }
      /**
       * <code>optional bytes protoData = 2;</code>
       *
       * <pre>
       *消息数据
       * </pre>
       */
      public Builder setProtoData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        protoData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes protoData = 2;</code>
       *
       * <pre>
       *消息数据
       * </pre>
       */
      public Builder clearProtoData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        protoData_ = getDefaultInstance().getProtoData();
        
        return this;
      }

      private int protoClientNo_ ;
      /**
       * <code>optional uint32 protoClientNo = 3;</code>
       *
       * <pre>
       *用于存放客户端流水号
       * </pre>
       */
      public boolean hasProtoClientNo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 protoClientNo = 3;</code>
       *
       * <pre>
       *用于存放客户端流水号
       * </pre>
       */
      public int getProtoClientNo() {
        return protoClientNo_;
      }
      /**
       * <code>optional uint32 protoClientNo = 3;</code>
       *
       * <pre>
       *用于存放客户端流水号
       * </pre>
       */
      public Builder setProtoClientNo(int value) {
        bitField0_ |= 0x00000004;
        protoClientNo_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 protoClientNo = 3;</code>
       *
       * <pre>
       *用于存放客户端流水号
       * </pre>
       */
      public Builder clearProtoClientNo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        protoClientNo_ = 0;
        
        return this;
      }

      private java.lang.Object protoBackExp_ = "";
      /**
       * <code>optional string protoBackExp = 4;</code>
       *
       * <pre>
       *用于存放后台模块的扩展信息
       * </pre>
       */
      public boolean hasProtoBackExp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string protoBackExp = 4;</code>
       *
       * <pre>
       *用于存放后台模块的扩展信息
       * </pre>
       */
      public java.lang.String getProtoBackExp() {
        java.lang.Object ref = protoBackExp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            protoBackExp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string protoBackExp = 4;</code>
       *
       * <pre>
       *用于存放后台模块的扩展信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getProtoBackExpBytes() {
        java.lang.Object ref = protoBackExp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          protoBackExp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string protoBackExp = 4;</code>
       *
       * <pre>
       *用于存放后台模块的扩展信息
       * </pre>
       */
      public Builder setProtoBackExp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        protoBackExp_ = value;
        
        return this;
      }
      /**
       * <code>optional string protoBackExp = 4;</code>
       *
       * <pre>
       *用于存放后台模块的扩展信息
       * </pre>
       */
      public Builder clearProtoBackExp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        protoBackExp_ = getDefaultInstance().getProtoBackExp();
        
        return this;
      }
      /**
       * <code>optional string protoBackExp = 4;</code>
       *
       * <pre>
       *用于存放后台模块的扩展信息
       * </pre>
       */
      public Builder setProtoBackExpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        protoBackExp_ = value;
        
        return this;
      }

      private java.lang.Object protoSource_ = "";
      /**
       * <code>optional string protoSource = 5;</code>
       *
       * <pre>
       *用于存放生产者源地址
       * </pre>
       */
      public boolean hasProtoSource() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string protoSource = 5;</code>
       *
       * <pre>
       *用于存放生产者源地址
       * </pre>
       */
      public java.lang.String getProtoSource() {
        java.lang.Object ref = protoSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            protoSource_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string protoSource = 5;</code>
       *
       * <pre>
       *用于存放生产者源地址
       * </pre>
       */
      public com.google.protobuf.ByteString
          getProtoSourceBytes() {
        java.lang.Object ref = protoSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          protoSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string protoSource = 5;</code>
       *
       * <pre>
       *用于存放生产者源地址
       * </pre>
       */
      public Builder setProtoSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        protoSource_ = value;
        
        return this;
      }
      /**
       * <code>optional string protoSource = 5;</code>
       *
       * <pre>
       *用于存放生产者源地址
       * </pre>
       */
      public Builder clearProtoSource() {
        bitField0_ = (bitField0_ & ~0x00000010);
        protoSource_ = getDefaultInstance().getProtoSource();
        
        return this;
      }
      /**
       * <code>optional string protoSource = 5;</code>
       *
       * <pre>
       *用于存放生产者源地址
       * </pre>
       */
      public Builder setProtoSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        protoSource_ = value;
        
        return this;
      }

      private int protoErrorCode_ ;
      /**
       * <code>optional uint32 protoErrorCode = 6;</code>
       *
       * <pre>
       *服务器返回错误码
       * </pre>
       */
      public boolean hasProtoErrorCode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 protoErrorCode = 6;</code>
       *
       * <pre>
       *服务器返回错误码
       * </pre>
       */
      public int getProtoErrorCode() {
        return protoErrorCode_;
      }
      /**
       * <code>optional uint32 protoErrorCode = 6;</code>
       *
       * <pre>
       *服务器返回错误码
       * </pre>
       */
      public Builder setProtoErrorCode(int value) {
        bitField0_ |= 0x00000020;
        protoErrorCode_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 protoErrorCode = 6;</code>
       *
       * <pre>
       *服务器返回错误码
       * </pre>
       */
      public Builder clearProtoErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        protoErrorCode_ = 0;
        
        return this;
      }

      private int protoEncrypt_ ;
      /**
       * <code>optional uint32 protoEncrypt = 7;</code>
       *
       * <pre>
       *是否加密，有值就是加密
       * </pre>
       */
      public boolean hasProtoEncrypt() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 protoEncrypt = 7;</code>
       *
       * <pre>
       *是否加密，有值就是加密
       * </pre>
       */
      public int getProtoEncrypt() {
        return protoEncrypt_;
      }
      /**
       * <code>optional uint32 protoEncrypt = 7;</code>
       *
       * <pre>
       *是否加密，有值就是加密
       * </pre>
       */
      public Builder setProtoEncrypt(int value) {
        bitField0_ |= 0x00000040;
        protoEncrypt_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 protoEncrypt = 7;</code>
       *
       * <pre>
       *是否加密，有值就是加密
       * </pre>
       */
      public Builder clearProtoEncrypt() {
        bitField0_ = (bitField0_ & ~0x00000040);
        protoEncrypt_ = 0;
        
        return this;
      }

      private java.lang.Object protoToken_ = "";
      /**
       * <code>optional string protoToken = 8;</code>
       *
       * <pre>
       *精简认证token
       * </pre>
       */
      public boolean hasProtoToken() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string protoToken = 8;</code>
       *
       * <pre>
       *精简认证token
       * </pre>
       */
      public java.lang.String getProtoToken() {
        java.lang.Object ref = protoToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            protoToken_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string protoToken = 8;</code>
       *
       * <pre>
       *精简认证token
       * </pre>
       */
      public com.google.protobuf.ByteString
          getProtoTokenBytes() {
        java.lang.Object ref = protoToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          protoToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string protoToken = 8;</code>
       *
       * <pre>
       *精简认证token
       * </pre>
       */
      public Builder setProtoToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        protoToken_ = value;
        
        return this;
      }
      /**
       * <code>optional string protoToken = 8;</code>
       *
       * <pre>
       *精简认证token
       * </pre>
       */
      public Builder clearProtoToken() {
        bitField0_ = (bitField0_ & ~0x00000080);
        protoToken_ = getDefaultInstance().getProtoToken();
        
        return this;
      }
      /**
       * <code>optional string protoToken = 8;</code>
       *
       * <pre>
       *精简认证token
       * </pre>
       */
      public Builder setProtoTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        protoToken_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MsgLiteInner)
    }

    static {
      defaultInstance = new MsgLiteInner(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MsgLiteInner)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
