// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushMsg.proto

package com.yuntongxun.mcm.core.protobuf;

public final class PushMsg {
  private PushMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PushMsgInnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PushMsgInner)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint64 version = 1;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional uint64 version = 1;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    long getVersion();

    /**
     * <code>optional uint32 msgType = 2;</code>
     *
     * <pre>
     *消息类型 1:文本消息 2：语音消息 3：视频消息  4：图片消息  5：位置消息  6：文件 
     * </pre>
     */
    boolean hasMsgType();
    /**
     * <code>optional uint32 msgType = 2;</code>
     *
     * <pre>
     *消息类型 1:文本消息 2：语音消息 3：视频消息  4：图片消息  5：位置消息  6：文件 
     * </pre>
     */
    int getMsgType();

    /**
     * <code>optional string msgId = 3;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    boolean hasMsgId();
    /**
     * <code>optional string msgId = 3;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    java.lang.String getMsgId();
    /**
     * <code>optional string msgId = 3;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>optional bytes msgContent = 4;</code>
     *
     * <pre>
     *文本消息内容
     * </pre>
     */
    boolean hasMsgContent();
    /**
     * <code>optional bytes msgContent = 4;</code>
     *
     * <pre>
     *文本消息内容
     * </pre>
     */
    com.google.protobuf.ByteString getMsgContent();

    /**
     * <code>optional string msgSender = 5;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    boolean hasMsgSender();
    /**
     * <code>optional string msgSender = 5;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    java.lang.String getMsgSender();
    /**
     * <code>optional string msgSender = 5;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgSenderBytes();

    /**
     * <code>optional string msgReceiver = 6;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    boolean hasMsgReceiver();
    /**
     * <code>optional string msgReceiver = 6;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    java.lang.String getMsgReceiver();
    /**
     * <code>optional string msgReceiver = 6;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgReceiverBytes();

    /**
     * <code>optional string msgDomain = 7;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    boolean hasMsgDomain();
    /**
     * <code>optional string msgDomain = 7;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    java.lang.String getMsgDomain();
    /**
     * <code>optional string msgDomain = 7;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgDomainBytes();

    /**
     * <code>optional string msgFileName = 8;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    boolean hasMsgFileName();
    /**
     * <code>optional string msgFileName = 8;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    java.lang.String getMsgFileName();
    /**
     * <code>optional string msgFileName = 8;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgFileNameBytes();

    /**
     * <code>optional string msgFileUrl = 9;</code>
     *
     * <pre>
     *消息下载地址
     * </pre>
     */
    boolean hasMsgFileUrl();
    /**
     * <code>optional string msgFileUrl = 9;</code>
     *
     * <pre>
     *消息下载地址
     * </pre>
     */
    java.lang.String getMsgFileUrl();
    /**
     * <code>optional string msgFileUrl = 9;</code>
     *
     * <pre>
     *消息下载地址
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgFileUrlBytes();

    /**
     * <code>optional string msgDateCreated = 10;</code>
     *
     * <pre>
     *服务器接收消息时间（ms）
     * </pre>
     */
    boolean hasMsgDateCreated();
    /**
     * <code>optional string msgDateCreated = 10;</code>
     *
     * <pre>
     *服务器接收消息时间（ms）
     * </pre>
     */
    java.lang.String getMsgDateCreated();
    /**
     * <code>optional string msgDateCreated = 10;</code>
     *
     * <pre>
     *服务器接收消息时间（ms）
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgDateCreatedBytes();

    /**
     * <code>optional uint32 msgCompressLen = 11;</code>
     *
     * <pre>
     *本文消息的源长度，如果消息内容经过压缩该字段大于0
     * </pre>
     */
    boolean hasMsgCompressLen();
    /**
     * <code>optional uint32 msgCompressLen = 11;</code>
     *
     * <pre>
     *本文消息的源长度，如果消息内容经过压缩该字段大于0
     * </pre>
     */
    int getMsgCompressLen();

    /**
     * <code>optional bytes msgData = 12;</code>
     *
     * <pre>
     *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
     * </pre>
     */
    boolean hasMsgData();
    /**
     * <code>optional bytes msgData = 12;</code>
     *
     * <pre>
     *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
     * </pre>
     */
    com.google.protobuf.ByteString getMsgData();

    /**
     * <code>optional string senderNickName = 13;</code>
     *
     * <pre>
     *发送者昵称
     * </pre>
     */
    boolean hasSenderNickName();
    /**
     * <code>optional string senderNickName = 13;</code>
     *
     * <pre>
     *发送者昵称
     * </pre>
     */
    java.lang.String getSenderNickName();
    /**
     * <code>optional string senderNickName = 13;</code>
     *
     * <pre>
     *发送者昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getSenderNickNameBytes();
  }
  /**
   * Protobuf type {@code PushMsgInner}
   */
  public static final class PushMsgInner extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:PushMsgInner)
      PushMsgInnerOrBuilder {
    // Use PushMsgInner.newBuilder() to construct.
    private PushMsgInner(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PushMsgInner(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final PushMsgInner defaultInstance;
    public static PushMsgInner getDefaultInstance() {
      return defaultInstance;
    }

    public PushMsgInner getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private PushMsgInner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              msgType_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              msgId_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              msgContent_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              msgSender_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              msgReceiver_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              msgDomain_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              msgFileName_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              msgFileUrl_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              msgDateCreated_ = bs;
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              msgCompressLen_ = input.readUInt32();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              msgData_ = input.readBytes();
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              senderNickName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<PushMsgInner> PARSER =
        new com.google.protobuf.AbstractParser<PushMsgInner>() {
      public PushMsgInner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushMsgInner(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PushMsgInner> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <code>optional uint64 version = 1;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 version = 1;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public long getVersion() {
      return version_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private int msgType_;
    /**
     * <code>optional uint32 msgType = 2;</code>
     *
     * <pre>
     *消息类型 1:文本消息 2：语音消息 3：视频消息  4：图片消息  5：位置消息  6：文件 
     * </pre>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 msgType = 2;</code>
     *
     * <pre>
     *消息类型 1:文本消息 2：语音消息 3：视频消息  4：图片消息  5：位置消息  6：文件 
     * </pre>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSGID_FIELD_NUMBER = 3;
    private java.lang.Object msgId_;
    /**
     * <code>optional string msgId = 3;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string msgId = 3;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgId = 3;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGCONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString msgContent_;
    /**
     * <code>optional bytes msgContent = 4;</code>
     *
     * <pre>
     *文本消息内容
     * </pre>
     */
    public boolean hasMsgContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes msgContent = 4;</code>
     *
     * <pre>
     *文本消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString getMsgContent() {
      return msgContent_;
    }

    public static final int MSGSENDER_FIELD_NUMBER = 5;
    private java.lang.Object msgSender_;
    /**
     * <code>optional string msgSender = 5;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public boolean hasMsgSender() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string msgSender = 5;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public java.lang.String getMsgSender() {
      java.lang.Object ref = msgSender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgSender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgSender = 5;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgSenderBytes() {
      java.lang.Object ref = msgSender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgSender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGRECEIVER_FIELD_NUMBER = 6;
    private java.lang.Object msgReceiver_;
    /**
     * <code>optional string msgReceiver = 6;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    public boolean hasMsgReceiver() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string msgReceiver = 6;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    public java.lang.String getMsgReceiver() {
      java.lang.Object ref = msgReceiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgReceiver_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgReceiver = 6;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgReceiverBytes() {
      java.lang.Object ref = msgReceiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgReceiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGDOMAIN_FIELD_NUMBER = 7;
    private java.lang.Object msgDomain_;
    /**
     * <code>optional string msgDomain = 7;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    public boolean hasMsgDomain() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string msgDomain = 7;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    public java.lang.String getMsgDomain() {
      java.lang.Object ref = msgDomain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgDomain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgDomain = 7;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgDomainBytes() {
      java.lang.Object ref = msgDomain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgDomain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGFILENAME_FIELD_NUMBER = 8;
    private java.lang.Object msgFileName_;
    /**
     * <code>optional string msgFileName = 8;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    public boolean hasMsgFileName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string msgFileName = 8;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    public java.lang.String getMsgFileName() {
      java.lang.Object ref = msgFileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgFileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgFileName = 8;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgFileNameBytes() {
      java.lang.Object ref = msgFileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGFILEURL_FIELD_NUMBER = 9;
    private java.lang.Object msgFileUrl_;
    /**
     * <code>optional string msgFileUrl = 9;</code>
     *
     * <pre>
     *消息下载地址
     * </pre>
     */
    public boolean hasMsgFileUrl() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string msgFileUrl = 9;</code>
     *
     * <pre>
     *消息下载地址
     * </pre>
     */
    public java.lang.String getMsgFileUrl() {
      java.lang.Object ref = msgFileUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgFileUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgFileUrl = 9;</code>
     *
     * <pre>
     *消息下载地址
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgFileUrlBytes() {
      java.lang.Object ref = msgFileUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgFileUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGDATECREATED_FIELD_NUMBER = 10;
    private java.lang.Object msgDateCreated_;
    /**
     * <code>optional string msgDateCreated = 10;</code>
     *
     * <pre>
     *服务器接收消息时间（ms）
     * </pre>
     */
    public boolean hasMsgDateCreated() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string msgDateCreated = 10;</code>
     *
     * <pre>
     *服务器接收消息时间（ms）
     * </pre>
     */
    public java.lang.String getMsgDateCreated() {
      java.lang.Object ref = msgDateCreated_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgDateCreated_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgDateCreated = 10;</code>
     *
     * <pre>
     *服务器接收消息时间（ms）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgDateCreatedBytes() {
      java.lang.Object ref = msgDateCreated_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgDateCreated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGCOMPRESSLEN_FIELD_NUMBER = 11;
    private int msgCompressLen_;
    /**
     * <code>optional uint32 msgCompressLen = 11;</code>
     *
     * <pre>
     *本文消息的源长度，如果消息内容经过压缩该字段大于0
     * </pre>
     */
    public boolean hasMsgCompressLen() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional uint32 msgCompressLen = 11;</code>
     *
     * <pre>
     *本文消息的源长度，如果消息内容经过压缩该字段大于0
     * </pre>
     */
    public int getMsgCompressLen() {
      return msgCompressLen_;
    }

    public static final int MSGDATA_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString msgData_;
    /**
     * <code>optional bytes msgData = 12;</code>
     *
     * <pre>
     *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
     * </pre>
     */
    public boolean hasMsgData() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional bytes msgData = 12;</code>
     *
     * <pre>
     *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
     * </pre>
     */
    public com.google.protobuf.ByteString getMsgData() {
      return msgData_;
    }

    public static final int SENDERNICKNAME_FIELD_NUMBER = 13;
    private java.lang.Object senderNickName_;
    /**
     * <code>optional string senderNickName = 13;</code>
     *
     * <pre>
     *发送者昵称
     * </pre>
     */
    public boolean hasSenderNickName() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string senderNickName = 13;</code>
     *
     * <pre>
     *发送者昵称
     * </pre>
     */
    public java.lang.String getSenderNickName() {
      java.lang.Object ref = senderNickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderNickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string senderNickName = 13;</code>
     *
     * <pre>
     *发送者昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSenderNickNameBytes() {
      java.lang.Object ref = senderNickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderNickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0L;
      msgType_ = 0;
      msgId_ = "";
      msgContent_ = com.google.protobuf.ByteString.EMPTY;
      msgSender_ = "";
      msgReceiver_ = "";
      msgDomain_ = "";
      msgFileName_ = "";
      msgFileUrl_ = "";
      msgDateCreated_ = "";
      msgCompressLen_ = 0;
      msgData_ = com.google.protobuf.ByteString.EMPTY;
      senderNickName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, msgType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, msgContent_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgSenderBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getMsgReceiverBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getMsgDomainBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getMsgFileNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getMsgFileUrlBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getMsgDateCreatedBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt32(11, msgCompressLen_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, msgData_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getSenderNickNameBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, msgType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, msgContent_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgSenderBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getMsgReceiverBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getMsgDomainBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getMsgFileNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getMsgFileUrlBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getMsgDateCreatedBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, msgCompressLen_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, msgData_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getSenderNickNameBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code PushMsgInner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:PushMsgInner)
        com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInnerOrBuilder {
      // Construct using com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        msgContent_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        msgSender_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        msgReceiver_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        msgDomain_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        msgFileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        msgFileUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        msgDateCreated_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        msgCompressLen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        msgData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000800);
        senderNickName_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner getDefaultInstanceForType() {
        return com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner.getDefaultInstance();
      }

      public com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner build() {
        com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner buildPartial() {
        com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner result = new com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.msgContent_ = msgContent_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgSender_ = msgSender_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgReceiver_ = msgReceiver_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msgDomain_ = msgDomain_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.msgFileName_ = msgFileName_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.msgFileUrl_ = msgFileUrl_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.msgDateCreated_ = msgDateCreated_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.msgCompressLen_ = msgCompressLen_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.msgData_ = msgData_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.senderNickName_ = senderNickName_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner other) {
        if (other == com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000004;
          msgId_ = other.msgId_;
          
        }
        if (other.hasMsgContent()) {
          setMsgContent(other.getMsgContent());
        }
        if (other.hasMsgSender()) {
          bitField0_ |= 0x00000010;
          msgSender_ = other.msgSender_;
          
        }
        if (other.hasMsgReceiver()) {
          bitField0_ |= 0x00000020;
          msgReceiver_ = other.msgReceiver_;
          
        }
        if (other.hasMsgDomain()) {
          bitField0_ |= 0x00000040;
          msgDomain_ = other.msgDomain_;
          
        }
        if (other.hasMsgFileName()) {
          bitField0_ |= 0x00000080;
          msgFileName_ = other.msgFileName_;
          
        }
        if (other.hasMsgFileUrl()) {
          bitField0_ |= 0x00000100;
          msgFileUrl_ = other.msgFileUrl_;
          
        }
        if (other.hasMsgDateCreated()) {
          bitField0_ |= 0x00000200;
          msgDateCreated_ = other.msgDateCreated_;
          
        }
        if (other.hasMsgCompressLen()) {
          setMsgCompressLen(other.getMsgCompressLen());
        }
        if (other.hasMsgData()) {
          setMsgData(other.getMsgData());
        }
        if (other.hasSenderNickName()) {
          bitField0_ |= 0x00001000;
          senderNickName_ = other.senderNickName_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yuntongxun.mcm.core.protobuf.PushMsg.PushMsgInner) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long version_ ;
      /**
       * <code>optional uint64 version = 1;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 version = 1;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <code>optional uint64 version = 1;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        
        return this;
      }
      /**
       * <code>optional uint64 version = 1;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        
        return this;
      }

      private int msgType_ ;
      /**
       * <code>optional uint32 msgType = 2;</code>
       *
       * <pre>
       *消息类型 1:文本消息 2：语音消息 3：视频消息  4：图片消息  5：位置消息  6：文件 
       * </pre>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 msgType = 2;</code>
       *
       * <pre>
       *消息类型 1:文本消息 2：语音消息 3：视频消息  4：图片消息  5：位置消息  6：文件 
       * </pre>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional uint32 msgType = 2;</code>
       *
       * <pre>
       *消息类型 1:文本消息 2：语音消息 3：视频消息  4：图片消息  5：位置消息  6：文件 
       * </pre>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000002;
        msgType_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 msgType = 2;</code>
       *
       * <pre>
       *消息类型 1:文本消息 2：语音消息 3：视频消息  4：图片消息  5：位置消息  6：文件 
       * </pre>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = 0;
        
        return this;
      }

      private java.lang.Object msgId_ = "";
      /**
       * <code>optional string msgId = 3;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string msgId = 3;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgId = 3;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgId = 3;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msgId_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgId = 3;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgId_ = getDefaultInstance().getMsgId();
        
        return this;
      }
      /**
       * <code>optional string msgId = 3;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msgId_ = value;
        
        return this;
      }

      private com.google.protobuf.ByteString msgContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msgContent = 4;</code>
       *
       * <pre>
       *文本消息内容
       * </pre>
       */
      public boolean hasMsgContent() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes msgContent = 4;</code>
       *
       * <pre>
       *文本消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString getMsgContent() {
        return msgContent_;
      }
      /**
       * <code>optional bytes msgContent = 4;</code>
       *
       * <pre>
       *文本消息内容
       * </pre>
       */
      public Builder setMsgContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        msgContent_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes msgContent = 4;</code>
       *
       * <pre>
       *文本消息内容
       * </pre>
       */
      public Builder clearMsgContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        msgContent_ = getDefaultInstance().getMsgContent();
        
        return this;
      }

      private java.lang.Object msgSender_ = "";
      /**
       * <code>optional string msgSender = 5;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public boolean hasMsgSender() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string msgSender = 5;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public java.lang.String getMsgSender() {
        java.lang.Object ref = msgSender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgSender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgSender = 5;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgSenderBytes() {
        java.lang.Object ref = msgSender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgSender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgSender = 5;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setMsgSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgSender_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgSender = 5;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder clearMsgSender() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgSender_ = getDefaultInstance().getMsgSender();
        
        return this;
      }
      /**
       * <code>optional string msgSender = 5;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setMsgSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgSender_ = value;
        
        return this;
      }

      private java.lang.Object msgReceiver_ = "";
      /**
       * <code>optional string msgReceiver = 6;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public boolean hasMsgReceiver() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string msgReceiver = 6;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public java.lang.String getMsgReceiver() {
        java.lang.Object ref = msgReceiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgReceiver_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgReceiver = 6;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgReceiverBytes() {
        java.lang.Object ref = msgReceiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgReceiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgReceiver = 6;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public Builder setMsgReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgReceiver_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgReceiver = 6;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public Builder clearMsgReceiver() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgReceiver_ = getDefaultInstance().getMsgReceiver();
        
        return this;
      }
      /**
       * <code>optional string msgReceiver = 6;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public Builder setMsgReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgReceiver_ = value;
        
        return this;
      }

      private java.lang.Object msgDomain_ = "";
      /**
       * <code>optional string msgDomain = 7;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public boolean hasMsgDomain() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string msgDomain = 7;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public java.lang.String getMsgDomain() {
        java.lang.Object ref = msgDomain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgDomain_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgDomain = 7;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgDomainBytes() {
        java.lang.Object ref = msgDomain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgDomain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgDomain = 7;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public Builder setMsgDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgDomain_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgDomain = 7;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public Builder clearMsgDomain() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgDomain_ = getDefaultInstance().getMsgDomain();
        
        return this;
      }
      /**
       * <code>optional string msgDomain = 7;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public Builder setMsgDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgDomain_ = value;
        
        return this;
      }

      private java.lang.Object msgFileName_ = "";
      /**
       * <code>optional string msgFileName = 8;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public boolean hasMsgFileName() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string msgFileName = 8;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public java.lang.String getMsgFileName() {
        java.lang.Object ref = msgFileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgFileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgFileName = 8;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgFileNameBytes() {
        java.lang.Object ref = msgFileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgFileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgFileName = 8;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public Builder setMsgFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        msgFileName_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgFileName = 8;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public Builder clearMsgFileName() {
        bitField0_ = (bitField0_ & ~0x00000080);
        msgFileName_ = getDefaultInstance().getMsgFileName();
        
        return this;
      }
      /**
       * <code>optional string msgFileName = 8;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public Builder setMsgFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        msgFileName_ = value;
        
        return this;
      }

      private java.lang.Object msgFileUrl_ = "";
      /**
       * <code>optional string msgFileUrl = 9;</code>
       *
       * <pre>
       *消息下载地址
       * </pre>
       */
      public boolean hasMsgFileUrl() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string msgFileUrl = 9;</code>
       *
       * <pre>
       *消息下载地址
       * </pre>
       */
      public java.lang.String getMsgFileUrl() {
        java.lang.Object ref = msgFileUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgFileUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgFileUrl = 9;</code>
       *
       * <pre>
       *消息下载地址
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgFileUrlBytes() {
        java.lang.Object ref = msgFileUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgFileUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgFileUrl = 9;</code>
       *
       * <pre>
       *消息下载地址
       * </pre>
       */
      public Builder setMsgFileUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        msgFileUrl_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgFileUrl = 9;</code>
       *
       * <pre>
       *消息下载地址
       * </pre>
       */
      public Builder clearMsgFileUrl() {
        bitField0_ = (bitField0_ & ~0x00000100);
        msgFileUrl_ = getDefaultInstance().getMsgFileUrl();
        
        return this;
      }
      /**
       * <code>optional string msgFileUrl = 9;</code>
       *
       * <pre>
       *消息下载地址
       * </pre>
       */
      public Builder setMsgFileUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        msgFileUrl_ = value;
        
        return this;
      }

      private java.lang.Object msgDateCreated_ = "";
      /**
       * <code>optional string msgDateCreated = 10;</code>
       *
       * <pre>
       *服务器接收消息时间（ms）
       * </pre>
       */
      public boolean hasMsgDateCreated() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string msgDateCreated = 10;</code>
       *
       * <pre>
       *服务器接收消息时间（ms）
       * </pre>
       */
      public java.lang.String getMsgDateCreated() {
        java.lang.Object ref = msgDateCreated_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgDateCreated_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgDateCreated = 10;</code>
       *
       * <pre>
       *服务器接收消息时间（ms）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgDateCreatedBytes() {
        java.lang.Object ref = msgDateCreated_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgDateCreated_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgDateCreated = 10;</code>
       *
       * <pre>
       *服务器接收消息时间（ms）
       * </pre>
       */
      public Builder setMsgDateCreated(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        msgDateCreated_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgDateCreated = 10;</code>
       *
       * <pre>
       *服务器接收消息时间（ms）
       * </pre>
       */
      public Builder clearMsgDateCreated() {
        bitField0_ = (bitField0_ & ~0x00000200);
        msgDateCreated_ = getDefaultInstance().getMsgDateCreated();
        
        return this;
      }
      /**
       * <code>optional string msgDateCreated = 10;</code>
       *
       * <pre>
       *服务器接收消息时间（ms）
       * </pre>
       */
      public Builder setMsgDateCreatedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        msgDateCreated_ = value;
        
        return this;
      }

      private int msgCompressLen_ ;
      /**
       * <code>optional uint32 msgCompressLen = 11;</code>
       *
       * <pre>
       *本文消息的源长度，如果消息内容经过压缩该字段大于0
       * </pre>
       */
      public boolean hasMsgCompressLen() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional uint32 msgCompressLen = 11;</code>
       *
       * <pre>
       *本文消息的源长度，如果消息内容经过压缩该字段大于0
       * </pre>
       */
      public int getMsgCompressLen() {
        return msgCompressLen_;
      }
      /**
       * <code>optional uint32 msgCompressLen = 11;</code>
       *
       * <pre>
       *本文消息的源长度，如果消息内容经过压缩该字段大于0
       * </pre>
       */
      public Builder setMsgCompressLen(int value) {
        bitField0_ |= 0x00000400;
        msgCompressLen_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 msgCompressLen = 11;</code>
       *
       * <pre>
       *本文消息的源长度，如果消息内容经过压缩该字段大于0
       * </pre>
       */
      public Builder clearMsgCompressLen() {
        bitField0_ = (bitField0_ & ~0x00000400);
        msgCompressLen_ = 0;
        
        return this;
      }

      private com.google.protobuf.ByteString msgData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msgData = 12;</code>
       *
       * <pre>
       *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
       * </pre>
       */
      public boolean hasMsgData() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional bytes msgData = 12;</code>
       *
       * <pre>
       *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
       * </pre>
       */
      public com.google.protobuf.ByteString getMsgData() {
        return msgData_;
      }
      /**
       * <code>optional bytes msgData = 12;</code>
       *
       * <pre>
       *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
       * </pre>
       */
      public Builder setMsgData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        msgData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes msgData = 12;</code>
       *
       * <pre>
       *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
       * </pre>
       */
      public Builder clearMsgData() {
        bitField0_ = (bitField0_ & ~0x00000800);
        msgData_ = getDefaultInstance().getMsgData();
        
        return this;
      }

      private java.lang.Object senderNickName_ = "";
      /**
       * <code>optional string senderNickName = 13;</code>
       *
       * <pre>
       *发送者昵称
       * </pre>
       */
      public boolean hasSenderNickName() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string senderNickName = 13;</code>
       *
       * <pre>
       *发送者昵称
       * </pre>
       */
      public java.lang.String getSenderNickName() {
        java.lang.Object ref = senderNickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderNickName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string senderNickName = 13;</code>
       *
       * <pre>
       *发送者昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSenderNickNameBytes() {
        java.lang.Object ref = senderNickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderNickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string senderNickName = 13;</code>
       *
       * <pre>
       *发送者昵称
       * </pre>
       */
      public Builder setSenderNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        senderNickName_ = value;
        
        return this;
      }
      /**
       * <code>optional string senderNickName = 13;</code>
       *
       * <pre>
       *发送者昵称
       * </pre>
       */
      public Builder clearSenderNickName() {
        bitField0_ = (bitField0_ & ~0x00001000);
        senderNickName_ = getDefaultInstance().getSenderNickName();
        
        return this;
      }
      /**
       * <code>optional string senderNickName = 13;</code>
       *
       * <pre>
       *发送者昵称
       * </pre>
       */
      public Builder setSenderNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        senderNickName_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PushMsgInner)
    }

    static {
      defaultInstance = new PushMsgInner(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PushMsgInner)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
