// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendMsg.proto

package com.yuntongxun.mcm.core.protobuf;

public final class SendMsg {
  private SendMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SendMsgInnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SendMsgInner)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 msgType = 1;</code>
     *
     * <pre>
     *消息类型 1:文本消息 2：语音消息 3：视频消息  4：表情消息  5：位置消息  6：文件 
     * </pre>
     */
    boolean hasMsgType();
    /**
     * <code>optional uint32 msgType = 1;</code>
     *
     * <pre>
     *消息类型 1:文本消息 2：语音消息 3：视频消息  4：表情消息  5：位置消息  6：文件 
     * </pre>
     */
    int getMsgType();

    /**
     * <code>optional string msgId = 2;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    boolean hasMsgId();
    /**
     * <code>optional string msgId = 2;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    java.lang.String getMsgId();
    /**
     * <code>optional string msgId = 2;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>optional bytes msgContent = 3;</code>
     *
     * <pre>
     *文本消息内容
     * </pre>
     */
    boolean hasMsgContent();
    /**
     * <code>optional bytes msgContent = 3;</code>
     *
     * <pre>
     *文本消息内容
     * </pre>
     */
    com.google.protobuf.ByteString getMsgContent();

    /**
     * <code>optional string msgSender = 4;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    boolean hasMsgSender();
    /**
     * <code>optional string msgSender = 4;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    java.lang.String getMsgSender();
    /**
     * <code>optional string msgSender = 4;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgSenderBytes();

    /**
     * <code>optional string msgReceiver = 5;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    boolean hasMsgReceiver();
    /**
     * <code>optional string msgReceiver = 5;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    java.lang.String getMsgReceiver();
    /**
     * <code>optional string msgReceiver = 5;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgReceiverBytes();

    /**
     * <code>optional string msgDomain = 6;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    boolean hasMsgDomain();
    /**
     * <code>optional string msgDomain = 6;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    java.lang.String getMsgDomain();
    /**
     * <code>optional string msgDomain = 6;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgDomainBytes();

    /**
     * <code>optional string msgFileName = 7;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    boolean hasMsgFileName();
    /**
     * <code>optional string msgFileName = 7;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    java.lang.String getMsgFileName();
    /**
     * <code>optional string msgFileName = 7;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgFileNameBytes();

    /**
     * <code>optional uint32 msgCompressLen = 8;</code>
     *
     * <pre>
     *本文消息的源长度，如果消息内容经过压缩该字段大于0
     * </pre>
     */
    boolean hasMsgCompressLen();
    /**
     * <code>optional uint32 msgCompressLen = 8;</code>
     *
     * <pre>
     *本文消息的源长度，如果消息内容经过压缩该字段大于0
     * </pre>
     */
    int getMsgCompressLen();

    /**
     * <code>optional bytes msgData = 9;</code>
     *
     * <pre>
     *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
     * </pre>
     */
    boolean hasMsgData();
    /**
     * <code>optional bytes msgData = 9;</code>
     *
     * <pre>
     *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
     * </pre>
     */
    com.google.protobuf.ByteString getMsgData();
  }
  /**
   * Protobuf type {@code SendMsgInner}
   */
  public static final class SendMsgInner extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:SendMsgInner)
      SendMsgInnerOrBuilder {
    // Use SendMsgInner.newBuilder() to construct.
    private SendMsgInner(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SendMsgInner(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final SendMsgInner defaultInstance;
    public static SendMsgInner getDefaultInstance() {
      return defaultInstance;
    }

    public SendMsgInner getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private SendMsgInner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              msgId_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msgContent_ = input.readBytes();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              msgSender_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              msgReceiver_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              msgDomain_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              msgFileName_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              msgCompressLen_ = input.readUInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              msgData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<SendMsgInner> PARSER =
        new com.google.protobuf.AbstractParser<SendMsgInner>() {
      public SendMsgInner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendMsgInner(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendMsgInner> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>optional uint32 msgType = 1;</code>
     *
     * <pre>
     *消息类型 1:文本消息 2：语音消息 3：视频消息  4：表情消息  5：位置消息  6：文件 
     * </pre>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 msgType = 1;</code>
     *
     * <pre>
     *消息类型 1:文本消息 2：语音消息 3：视频消息  4：表情消息  5：位置消息  6：文件 
     * </pre>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSGID_FIELD_NUMBER = 2;
    private java.lang.Object msgId_;
    /**
     * <code>optional string msgId = 2;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msgId = 2;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgId = 2;</code>
     *
     * <pre>
     *消息ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGCONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString msgContent_;
    /**
     * <code>optional bytes msgContent = 3;</code>
     *
     * <pre>
     *文本消息内容
     * </pre>
     */
    public boolean hasMsgContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes msgContent = 3;</code>
     *
     * <pre>
     *文本消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString getMsgContent() {
      return msgContent_;
    }

    public static final int MSGSENDER_FIELD_NUMBER = 4;
    private java.lang.Object msgSender_;
    /**
     * <code>optional string msgSender = 4;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public boolean hasMsgSender() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string msgSender = 4;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public java.lang.String getMsgSender() {
      java.lang.Object ref = msgSender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgSender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgSender = 4;</code>
     *
     * <pre>
     *发送者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgSenderBytes() {
      java.lang.Object ref = msgSender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgSender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGRECEIVER_FIELD_NUMBER = 5;
    private java.lang.Object msgReceiver_;
    /**
     * <code>optional string msgReceiver = 5;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    public boolean hasMsgReceiver() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string msgReceiver = 5;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    public java.lang.String getMsgReceiver() {
      java.lang.Object ref = msgReceiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgReceiver_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgReceiver = 5;</code>
     *
     * <pre>
     *接收者账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgReceiverBytes() {
      java.lang.Object ref = msgReceiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgReceiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGDOMAIN_FIELD_NUMBER = 6;
    private java.lang.Object msgDomain_;
    /**
     * <code>optional string msgDomain = 6;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    public boolean hasMsgDomain() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string msgDomain = 6;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    public java.lang.String getMsgDomain() {
      java.lang.Object ref = msgDomain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgDomain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgDomain = 6;</code>
     *
     * <pre>
     *需要扩展的消息字段放在这里
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgDomainBytes() {
      java.lang.Object ref = msgDomain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgDomain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGFILENAME_FIELD_NUMBER = 7;
    private java.lang.Object msgFileName_;
    /**
     * <code>optional string msgFileName = 7;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    public boolean hasMsgFileName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string msgFileName = 7;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    public java.lang.String getMsgFileName() {
      java.lang.Object ref = msgFileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgFileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgFileName = 7;</code>
     *
     * <pre>
     *消息文件名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgFileNameBytes() {
      java.lang.Object ref = msgFileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGCOMPRESSLEN_FIELD_NUMBER = 8;
    private int msgCompressLen_;
    /**
     * <code>optional uint32 msgCompressLen = 8;</code>
     *
     * <pre>
     *本文消息的源长度，如果消息内容经过压缩该字段大于0
     * </pre>
     */
    public boolean hasMsgCompressLen() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 msgCompressLen = 8;</code>
     *
     * <pre>
     *本文消息的源长度，如果消息内容经过压缩该字段大于0
     * </pre>
     */
    public int getMsgCompressLen() {
      return msgCompressLen_;
    }

    public static final int MSGDATA_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString msgData_;
    /**
     * <code>optional bytes msgData = 9;</code>
     *
     * <pre>
     *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
     * </pre>
     */
    public boolean hasMsgData() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bytes msgData = 9;</code>
     *
     * <pre>
     *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
     * </pre>
     */
    public com.google.protobuf.ByteString getMsgData() {
      return msgData_;
    }

    private void initFields() {
      msgType_ = 0;
      msgId_ = "";
      msgContent_ = com.google.protobuf.ByteString.EMPTY;
      msgSender_ = "";
      msgReceiver_ = "";
      msgDomain_ = "";
      msgFileName_ = "";
      msgCompressLen_ = 0;
      msgData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, msgContent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMsgSenderBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgReceiverBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getMsgDomainBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getMsgFileNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, msgCompressLen_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, msgData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, msgContent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMsgSenderBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgReceiverBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getMsgDomainBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getMsgFileNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, msgCompressLen_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, msgData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code SendMsgInner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:SendMsgInner)
        com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInnerOrBuilder {
      // Construct using com.yuntongxun.logic.core.protobuf.SendMsg.SendMsgInner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        msgContent_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        msgSender_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgReceiver_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        msgDomain_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        msgFileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        msgCompressLen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        msgData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner getDefaultInstanceForType() {
        return com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner.getDefaultInstance();
      }

      public com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner build() {
        com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner buildPartial() {
        com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner result = new com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgContent_ = msgContent_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.msgSender_ = msgSender_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgReceiver_ = msgReceiver_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgDomain_ = msgDomain_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msgFileName_ = msgFileName_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.msgCompressLen_ = msgCompressLen_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.msgData_ = msgData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner other) {
        if (other == com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000002;
          msgId_ = other.msgId_;
          
        }
        if (other.hasMsgContent()) {
          setMsgContent(other.getMsgContent());
        }
        if (other.hasMsgSender()) {
          bitField0_ |= 0x00000008;
          msgSender_ = other.msgSender_;
          
        }
        if (other.hasMsgReceiver()) {
          bitField0_ |= 0x00000010;
          msgReceiver_ = other.msgReceiver_;
          
        }
        if (other.hasMsgDomain()) {
          bitField0_ |= 0x00000020;
          msgDomain_ = other.msgDomain_;
          
        }
        if (other.hasMsgFileName()) {
          bitField0_ |= 0x00000040;
          msgFileName_ = other.msgFileName_;
          
        }
        if (other.hasMsgCompressLen()) {
          setMsgCompressLen(other.getMsgCompressLen());
        }
        if (other.hasMsgData()) {
          setMsgData(other.getMsgData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yuntongxun.mcm.core.protobuf.SendMsg.SendMsgInner) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgType_ ;
      /**
       * <code>optional uint32 msgType = 1;</code>
       *
       * <pre>
       *消息类型 1:文本消息 2：语音消息 3：视频消息  4：表情消息  5：位置消息  6：文件 
       * </pre>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 msgType = 1;</code>
       *
       * <pre>
       *消息类型 1:文本消息 2：语音消息 3：视频消息  4：表情消息  5：位置消息  6：文件 
       * </pre>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional uint32 msgType = 1;</code>
       *
       * <pre>
       *消息类型 1:文本消息 2：语音消息 3：视频消息  4：表情消息  5：位置消息  6：文件 
       * </pre>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 msgType = 1;</code>
       *
       * <pre>
       *消息类型 1:文本消息 2：语音消息 3：视频消息  4：表情消息  5：位置消息  6：文件 
       * </pre>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        
        return this;
      }

      private java.lang.Object msgId_ = "";
      /**
       * <code>optional string msgId = 2;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msgId = 2;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgId = 2;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgId = 2;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgId_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgId = 2;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = getDefaultInstance().getMsgId();
        
        return this;
      }
      /**
       * <code>optional string msgId = 2;</code>
       *
       * <pre>
       *消息ID
       * </pre>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgId_ = value;
        
        return this;
      }

      private com.google.protobuf.ByteString msgContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msgContent = 3;</code>
       *
       * <pre>
       *文本消息内容
       * </pre>
       */
      public boolean hasMsgContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes msgContent = 3;</code>
       *
       * <pre>
       *文本消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString getMsgContent() {
        return msgContent_;
      }
      /**
       * <code>optional bytes msgContent = 3;</code>
       *
       * <pre>
       *文本消息内容
       * </pre>
       */
      public Builder setMsgContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msgContent_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes msgContent = 3;</code>
       *
       * <pre>
       *文本消息内容
       * </pre>
       */
      public Builder clearMsgContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgContent_ = getDefaultInstance().getMsgContent();
        
        return this;
      }

      private java.lang.Object msgSender_ = "";
      /**
       * <code>optional string msgSender = 4;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public boolean hasMsgSender() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string msgSender = 4;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public java.lang.String getMsgSender() {
        java.lang.Object ref = msgSender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgSender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgSender = 4;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgSenderBytes() {
        java.lang.Object ref = msgSender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgSender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgSender = 4;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setMsgSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        msgSender_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgSender = 4;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder clearMsgSender() {
        bitField0_ = (bitField0_ & ~0x00000008);
        msgSender_ = getDefaultInstance().getMsgSender();
        
        return this;
      }
      /**
       * <code>optional string msgSender = 4;</code>
       *
       * <pre>
       *发送者账号
       * </pre>
       */
      public Builder setMsgSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        msgSender_ = value;
        
        return this;
      }

      private java.lang.Object msgReceiver_ = "";
      /**
       * <code>optional string msgReceiver = 5;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public boolean hasMsgReceiver() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string msgReceiver = 5;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public java.lang.String getMsgReceiver() {
        java.lang.Object ref = msgReceiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgReceiver_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgReceiver = 5;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgReceiverBytes() {
        java.lang.Object ref = msgReceiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgReceiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgReceiver = 5;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public Builder setMsgReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgReceiver_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgReceiver = 5;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public Builder clearMsgReceiver() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgReceiver_ = getDefaultInstance().getMsgReceiver();
        
        return this;
      }
      /**
       * <code>optional string msgReceiver = 5;</code>
       *
       * <pre>
       *接收者账号
       * </pre>
       */
      public Builder setMsgReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgReceiver_ = value;
        
        return this;
      }

      private java.lang.Object msgDomain_ = "";
      /**
       * <code>optional string msgDomain = 6;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public boolean hasMsgDomain() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string msgDomain = 6;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public java.lang.String getMsgDomain() {
        java.lang.Object ref = msgDomain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgDomain_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgDomain = 6;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgDomainBytes() {
        java.lang.Object ref = msgDomain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgDomain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgDomain = 6;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public Builder setMsgDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgDomain_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgDomain = 6;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public Builder clearMsgDomain() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgDomain_ = getDefaultInstance().getMsgDomain();
        
        return this;
      }
      /**
       * <code>optional string msgDomain = 6;</code>
       *
       * <pre>
       *需要扩展的消息字段放在这里
       * </pre>
       */
      public Builder setMsgDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgDomain_ = value;
        
        return this;
      }

      private java.lang.Object msgFileName_ = "";
      /**
       * <code>optional string msgFileName = 7;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public boolean hasMsgFileName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string msgFileName = 7;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public java.lang.String getMsgFileName() {
        java.lang.Object ref = msgFileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgFileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgFileName = 7;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgFileNameBytes() {
        java.lang.Object ref = msgFileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgFileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgFileName = 7;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public Builder setMsgFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgFileName_ = value;
        
        return this;
      }
      /**
       * <code>optional string msgFileName = 7;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public Builder clearMsgFileName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgFileName_ = getDefaultInstance().getMsgFileName();
        
        return this;
      }
      /**
       * <code>optional string msgFileName = 7;</code>
       *
       * <pre>
       *消息文件名
       * </pre>
       */
      public Builder setMsgFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgFileName_ = value;
        
        return this;
      }

      private int msgCompressLen_ ;
      /**
       * <code>optional uint32 msgCompressLen = 8;</code>
       *
       * <pre>
       *本文消息的源长度，如果消息内容经过压缩该字段大于0
       * </pre>
       */
      public boolean hasMsgCompressLen() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint32 msgCompressLen = 8;</code>
       *
       * <pre>
       *本文消息的源长度，如果消息内容经过压缩该字段大于0
       * </pre>
       */
      public int getMsgCompressLen() {
        return msgCompressLen_;
      }
      /**
       * <code>optional uint32 msgCompressLen = 8;</code>
       *
       * <pre>
       *本文消息的源长度，如果消息内容经过压缩该字段大于0
       * </pre>
       */
      public Builder setMsgCompressLen(int value) {
        bitField0_ |= 0x00000080;
        msgCompressLen_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 msgCompressLen = 8;</code>
       *
       * <pre>
       *本文消息的源长度，如果消息内容经过压缩该字段大于0
       * </pre>
       */
      public Builder clearMsgCompressLen() {
        bitField0_ = (bitField0_ & ~0x00000080);
        msgCompressLen_ = 0;
        
        return this;
      }

      private com.google.protobuf.ByteString msgData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msgData = 9;</code>
       *
       * <pre>
       *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
       * </pre>
       */
      public boolean hasMsgData() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes msgData = 9;</code>
       *
       * <pre>
       *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
       * </pre>
       */
      public com.google.protobuf.ByteString getMsgData() {
        return msgData_;
      }
      /**
       * <code>optional bytes msgData = 9;</code>
       *
       * <pre>
       *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
       * </pre>
       */
      public Builder setMsgData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        msgData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes msgData = 9;</code>
       *
       * <pre>
       *语音数据 注意：为了保持跟发送文本的一致体验，把60s语音当做特殊文本，必须经过压缩（小于60K），才允许使用该字段。
       * </pre>
       */
      public Builder clearMsgData() {
        bitField0_ = (bitField0_ & ~0x00000100);
        msgData_ = getDefaultInstance().getMsgData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SendMsgInner)
    }

    static {
      defaultInstance = new SendMsgInner(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SendMsgInner)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
